name: Deploy Flutter Web to GitHub Pages (Other Repo)

on:
    push:
        branches:
            - main # Change if your default branch is different

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1️⃣ Checkout the source code
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "stable"

            - name: Install dependencies
              run: flutter pub get

            - name: Build Flutter web
              run: flutter build web

            # 2️⃣ Set up Flutter
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: stable

            # 3️⃣ Install dependencies
            - name: Install dependencies
              run: flutter pub get

            # 4️⃣ Build Flutter web
            - name: Build Flutter web
              run: flutter build web

            # 5️⃣ Fix routing for GitHub Pages
            - name: Add 404.html for Flutter routing
              run: |
                  cp build/web/index.html build/web/404.html

            # 6️⃣ Deploy to GitHub Pages (other repo)
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GH_PAT }}
                  publish_dir: build/web
                  destination_repo: Expense-Revolution/koshik.github.io
                  user_name: GitHub Actions
                  user_email: actions@github.com
